version: '2'
services:
    whmapper-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/whmapper/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=whmapper
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
